/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 11:52:01 GMT 2024
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.calculator.Calculator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calculator_ESTest extends Calculator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.multiply((-468), (-468));
      assertEquals(219024, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.substract(1, 1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.substract(0, (-3343));
      assertEquals(3343, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.multiply(0, (-1698));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.multiply((-3343), 1);
      assertEquals((-3343), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.add(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.add((-5365), (-3343));
      assertEquals((-8708), int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.substract((-3343), 2022);
      assertEquals((-5365), int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.add(0, 1);
      assertEquals(1, int0);
  }
}
